"""Prototype procurement review reports with implemented checks and officer notes.
Reports do not certify eligibility, authenticity or legal compliance.
"""
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.units import inch
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable, KeepTogether
)
from reportlab.pdfgen import canvas
import os
import datetime
from xml.sax.saxutils import escape


def escape_report_values(value):
    """Render supplied evidence and officer notes as text, never ReportLab markup."""
    if isinstance(value, str):
        return escape(value)
    if isinstance(value, dict):
        return {key: escape_report_values(item) for key, item in value.items()}
    if isinstance(value, list):
        return [escape_report_values(item) for item in value]
    return value


class OfficialReportCanvas(canvas.Canvas):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = max(1, len(self._saved_page_states))
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self._draw_decorations(num_pages)
            super().showPage()
        super().save()

    def _draw_decorations(self, total_pages):
        self.saveState()
        # Official Header (Pure Black & White)
        self.setFont("Helvetica-Bold", 8)
        self.setFillColor(colors.black)
        self.drawString(40, 755, "BIDLENS AI - PROCUREMENT REVIEW REPORT")
        self.setFont("Helvetica", 8)
        self.setFont("Helvetica", 6)
        self.drawRightString(572, 741, "PROTOTYPE DEMONSTRATION RECORD - FOR OFFICER REVIEW")
        self.setStrokeColor(colors.black)
        self.setLineWidth(0.75)
        self.line(40, 736, 572, 736)

        # Official Footer (Pure Black & White)
        self.line(40, 36, 572, 36)
        self.setFont("Helvetica", 7.5)
        self.drawString(40, 26, "Generated by BidLens AI Platform | Prototype Demonstration Report for Human Officer Review")
        self.drawRightString(572, 26, f"Page {self._pageNumber} of {total_pages}")
        self.restoreState()


def generate_certified_audit_pdf(
    audit_data: dict,
    output_filepath: str,
    officer_name: str = None,
    officer_designation: str = None,
    officer_overrides: dict = None,
    **kwargs
) -> str:
    """
    Builds a prototype procurement review report with the recorded officer decision log
    and manual physical sign-off box with smooth document flow (no awkward empty page gaps).
    """
    audit_data = escape_report_values(audit_data)
    officer_overrides = escape_report_values(officer_overrides)
    officer_name = escape_report_values(officer_name)
    officer_designation = escape_report_values(officer_designation)
    out_dir = os.path.dirname(os.path.abspath(output_filepath))
    if out_dir:
        os.makedirs(out_dir, exist_ok=True)

    doc = SimpleDocTemplate(
        output_filepath,
        pagesize=letter,
        leftMargin=36,
        rightMargin=36,
        topMargin=62,
        bottomMargin=44
    )

    styles = getSampleStyleSheet()

    # Black & White Compact Professional Styles
    title_style = ParagraphStyle(
        'BWTitle',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=12,
        leading=15,
        textColor=colors.black,
        spaceAfter=1
    )
    subtitle_style = ParagraphStyle(
        'BWSubtitle',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=8,
        leading=10,
        textColor=colors.black,
        spaceAfter=4
    )
    h1_style = ParagraphStyle(
        'BWH1',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=9,
        leading=11.5,
        textColor=colors.black,
        spaceBefore=6,
        spaceAfter=2
    )
    body_style = ParagraphStyle(
        'BWBody',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=7.5,
        leading=9.5,
        textColor=colors.black
    )
    body_bold = ParagraphStyle(
        'BWBodyBold',
        parent=body_style,
        fontName='Helvetica-Bold'
    )
    callout_style = ParagraphStyle(
        'BWCallout',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=7.5,
        leading=10,
        textColor=colors.black
    )

    story = []

    file_info = audit_data.get("file_info", {})
    comp_sum = audit_data.get("compliance_summary", {})
    risk_info = audit_data.get("rejection_risk_analysis", {})
    value_spot = audit_data.get("value_spotlight", {})
    clauses = audit_data.get("clause_level_decisions", [])
    contradictions = audit_data.get("contradictions_detected", [])
    govt = audit_data.get("government_verification", {})

    vendor_name = file_info.get("vendor_name", "Vendor Legal Entity")
    filename = file_info.get("filename", "document.pdf")
    status_text = comp_sum.get("overall_status", "PENDING")
    risk_tier = comp_sum.get("risk_tier", "LOW")
    eval_officer = officer_name or "Procurement Officer"
    eval_designation = officer_designation or "Senior Procurement Officer"
    active_tender_id = audit_data.get("tender_id") or "GEM/2026/B/892100"

    risk_score_raw = risk_info.get('risk_score')
    risk_score_pct = (risk_score_raw if risk_score_raw is not None else 0.0) * 100

    # ── 1. Document Title & Header ────────────────────────────
    story.append(Paragraph("PROCUREMENT REVIEW REPORT (PROTOTYPE)", title_style))
    story.append(Paragraph(f"Tender Ref: {active_tender_id} | Report Generated: {datetime.datetime.now().strftime('%d-%b-%Y %H:%M:%S')}", subtitle_style))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.black, spaceBefore=1, spaceAfter=4))
    if audit_data.get('evaluation_id'):
        story.append(Paragraph(f"Evaluation ID: {audit_data['evaluation_id']} | Machine evaluated: {audit_data.get('evaluated_at', 'Unavailable')}", subtitle_style))
    if audit_data.get('parent_evaluation_id'):
        story.append(Paragraph(f"Original evaluation: {audit_data['parent_evaluation_id']} | Linked revised submission; machine comparison is separate from officer decisions.", subtitle_style))
    checklist = audit_data.get('submission_checklist', [])
    if checklist:
        story.append(Paragraph("Submission receipt checklist (officer-defined)", h1_style))
        story.append(Paragraph("Receipt is not proof of authenticity or compliance. These attachments are not merged into the rule audit. Session records reset on backend restart.", body_style))
        for item in checklist:
            story.append(Paragraph(f"{item['name']}: {item['receipt_status']} | {item.get('filename') or 'No file assigned'}", body_style))


    # ── 2. Executive Overview Table (Black & White) ───────────
    passed = comp_sum.get('passed', 0)
    exempt = comp_sum.get('exempt', 0)
    failed = comp_sum.get('failed', 0)
    needs_review = comp_sum.get('needs_review', 0)
    na = comp_sum.get('not_applicable', 0)
    total_clauses = comp_sum.get('total_clauses_checked', 0)

    overview_data = [
        [
            Paragraph(f"<b>Vendor Legal Entity:</b> {vendor_name}", body_style),
            Paragraph(f"<b>Submission File:</b> {filename}", body_style),
        ],
        [
            Paragraph(f"<b>Outcome of Evaluated Checks:</b> <b>{status_text}</b>", body_style),
            Paragraph(f"<b>Heuristic Review Risk Tier:</b> <b>{risk_tier}</b> (Index: {risk_score_pct:.0f}/100; not a probability)", body_style),
        ],
        [
            Paragraph(f"<b>Clauses Evaluated ({total_clauses}):</b> Pass: {passed} | Exempt: {exempt} | Fail: {failed} | Review: {needs_review} | N/A: {na}", body_style),
            Paragraph(f"<b>Offline Identity Checks:</b> {govt.get('overall_govt_verification', 'UNVERIFIED (OFFLINE PROTOTYPE)')}", body_style),
        ]
    ]

    t_overview = Table(overview_data, colWidths=[3.7*inch, 3.7*inch])
    t_overview.setStyle(TableStyle([
        ('BOX', (0,0), (-1,-1), 1, colors.black),
        ('INNERGRID', (0,0), (-1,-1), 0.5, colors.black),
        ('TOPPADDING', (0,0), (-1,-1), 2),
        ('BOTTOMPADDING', (0,0), (-1,-1), 2),
        ('LEFTPADDING', (0,0), (-1,-1), 4),
        ('RIGHTPADDING', (0,0), (-1,-1), 4),
    ]))
    story.append(t_overview)
    story.append(Spacer(1, 2))

    # ── 3. Executive Summary Callout ──────────────────────────
    exec_summary = audit_data.get("executive_summary", "")
    exec_box = Table([[Paragraph(f"<b>Executive Summary & Recommendation:</b> {exec_summary}", callout_style)]], colWidths=[7.4*inch])
    exec_box.setStyle(TableStyle([
        ('BOX', (0,0), (-1,-1), 1, colors.black),
        ('TOPPADDING', (0,0), (-1,-1), 2.5),
        ('BOTTOMPADDING', (0,0), (-1,-1), 2.5),
        ('LEFTPADDING', (0,0), (-1,-1), 4),
        ('RIGHTPADDING', (0,0), (-1,-1), 4),
    ]))
    story.append(exec_box)
    story.append(Spacer(1, 2))

    # ── 4. Value-for-Money Spotlight (If Applicable) ──────────
    if value_spot.get("is_spotlight_candidate"):
        story.append(Paragraph("Value-for-Money Advantage & MSME Highlights", h1_style))
        spotlight_items = []
        for perk in value_spot.get("value_highlights", []):
            spotlight_items.append(Paragraph(f"- {perk}", body_style))
        
        t_spot = Table([[item] for item in spotlight_items], colWidths=[7.4*inch])
        t_spot.setStyle(TableStyle([
            ('BOX', (0,0), (-1,-1), 1, colors.black),
            ('TOPPADDING', (0,0), (-1,-1), 2),
            ('BOTTOMPADDING', (0,0), (-1,-1), 2),
            ('LEFTPADDING', (0,0), (-1,-1), 4),
            ('RIGHTPADDING', (0,0), (-1,-1), 4),
        ]))
        story.append(t_spot)
        story.append(Spacer(1, 2))

    # ── Government Portal Gateway Cross-Verification ──────────
    gateways = govt.get("gateways", [])
    if gateways:
        story.append(Paragraph("Offline Identity Checks & Unverified Registry Status", h1_style))
        gw_table_data = [
            [
                Paragraph("<b>Portal / Registry</b>", body_bold),
                Paragraph("<b>Status Verification</b>", body_bold),
                Paragraph("<b>Audit Sync Details</b>", body_bold)
            ]
        ]
        for gw in gateways:
            gw_details = gw.get("details", {})
            desc_items = [f"{k.replace('_', ' ').title()}: {v}" for k, v in gw_details.items() if k not in ["portal", "valid_format", "valid"]]
            gw_table_data.append([
                Paragraph(gw.get("name", ""), body_style),
                Paragraph(f"<b>{gw.get('status', '')}</b>", body_style),
                Paragraph(" | ".join(desc_items) if desc_items else "Live registry unverified", body_style)
            ])
        t_gw = Table(gw_table_data, colWidths=[2.2*inch, 1.8*inch, 3.4*inch])
        t_gw.setStyle(TableStyle([
            ('BOX', (0,0), (-1,-1), 1, colors.black),
            ('INNERGRID', (0,0), (-1,-1), 0.5, colors.black),
            ('LINEBELOW', (0,0), (-1,0), 1.2, colors.black),
            ('TOPPADDING', (0,0), (-1,-1), 1.5),
            ('BOTTOMPADDING', (0,0), (-1,-1), 1.5),
            ('LEFTPADDING', (0,0), (-1,-1), 3.5),
            ('RIGHTPADDING', (0,0), (-1,-1), 3.5),
        ]))
        story.append(t_gw)
        story.append(Spacer(1, 2))

    # ── 5. Clause-by-Clause Compliance Matrix (Black & White) ─
    story.append(Paragraph("Implemented Requirement Checks & Evidence Summaries", h1_style))
    clause_table_data = [
        [
            Paragraph("<b>Clause ID</b>", body_bold),
            Paragraph("<b>Requirement Name</b>", body_bold),
            Paragraph("<b>Status</b>", body_bold),
            Paragraph("<b>Regulatory Rule & Extracted Evidence Trace</b>", body_bold)
        ]
    ]

    for c in clauses:
        st = c.get("status", "PENDING").replace("_", " ")
        cid = c.get("clause_id")
        # Check if overridden by officer
        if officer_overrides and cid in officer_overrides:
            st = officer_overrides[cid].get("status", st).replace("_", " ") + "<br/><font size='6'>Officer decision</font>"

        reg_ref = str(c.get('regulation_ref', 'N/A') or 'N/A')
        evidence_txt = str(c.get('evidence', 'N/A') or 'N/A')
        c_name = str(c.get("clause_name", "") or "")
        clause_table_data.append([
            Paragraph(f"<b>{cid}</b>", body_style),
            Paragraph(c_name, body_style),
            Paragraph(f"<b>{st}</b>", body_style),
            Paragraph(f"<b>Rule:</b> {reg_ref}<br/><b>Evidence:</b> {evidence_txt}", body_style)
        ])

    t_clauses = Table(clause_table_data, colWidths=[1.12*inch, 1.68*inch, 0.9*inch, 3.7*inch])
    t_clauses.setStyle(TableStyle([
        ('BOX', (0,0), (-1,-1), 1, colors.black),
        ('INNERGRID', (0,0), (-1,-1), 0.5, colors.black),
        ('LINEBELOW', (0,0), (-1,0), 1.2, colors.black),
        ('TOPPADDING', (0,0), (-1,-1), 2),
        ('BOTTOMPADDING', (0,0), (-1,-1), 2),
        ('LEFTPADDING', (0,0), (-1,-1), 3.5),
        ('RIGHTPADDING', (0,0), (-1,-1), 3.5),
    ]))
    story.append(t_clauses)
    story.append(Spacer(1, 2))

    # ── 6. Contradictions & Discrepancies (If any) ────────────
    if contradictions:
        story.append(Paragraph("Configured Discrepancy Checks Within Submitted File", h1_style))
        contra_data = [
            [
                Paragraph("<b>Discrepancy Title</b>", body_bold),
                Paragraph("<b>Severity</b>", body_bold),
                Paragraph("<b>Finding & Impact</b>", body_bold)
            ]
        ]
        for ct in contradictions:
            contra_data.append([
                Paragraph(ct.get("title", ""), body_style),
                Paragraph(f"<b>{ct.get('severity')}</b>", body_style),
                Paragraph(f"<b>Description:</b> {ct.get('description')}<br/><b>Action Required:</b> {ct.get('remedy')}", body_style)
            ])

        t_contra = Table(contra_data, colWidths=[1.8*inch, 0.9*inch, 4.7*inch])
        t_contra.setStyle(TableStyle([
            ('BOX', (0,0), (-1,-1), 1, colors.black),
            ('INNERGRID', (0,0), (-1,-1), 0.5, colors.black),
            ('LINEBELOW', (0,0), (-1,0), 1.2, colors.black),
            ('TOPPADDING', (0,0), (-1,-1), 2),
            ('BOTTOMPADDING', (0,0), (-1,-1), 2),
            ('LEFTPADDING', (0,0), (-1,-1), 3.5),
            ('RIGHTPADDING', (0,0), (-1,-1), 3.5),
        ]))
        story.append(t_contra)
        story.append(Spacer(1, 2))

    # ── 7. Officer Sign-Off Block (Manual Physical Sign-Off) ───
    sign_off_start = len(story)
    story.append(Paragraph("Procurement Officer Evaluation & Manual Physical Sign-Off", h1_style))

    sign_off_data = [
        [
            Paragraph(f"<b>Evaluated By:</b> BidLens implemented checks", body_style),
            Paragraph(f"<b>Procurement Officer:</b> {eval_officer}", body_style),
        ],
        [
            Paragraph(f"<b>Source SHA-256:</b> {audit_data.get('file_info', {}).get('source_sha256', 'NOT RECORDED')}", body_style),
            Paragraph(f"<b>Designation:</b> {eval_designation}", body_style),
        ],
        [
            Paragraph(f"<b>Evaluation Timestamp:</b> {datetime.datetime.now().strftime('%d-%b-%Y %H:%M:%S')}", body_style),
            Paragraph(f"<b>Decision Status:</b> {status_text}", body_style),
        ],
        [
            Paragraph(
                "<b>Optional Manual Sign-Off:</b><br/><br/>"
                "___________________________________________________<br/>"
                "<i>Officer signature on printout (not digitally authenticated)</i>",
                body_style
            ),
            Paragraph(
                "<b>Procurement Advisory Notice:</b><br/>"
                "This report covers implemented checks against supplied tender criteria. It does not authenticate documents, verify live registries or certify legal eligibility. "
                "Any supervisory override is recorded below with officer justification.",
                body_style
            )
        ]
    ]

    t_sign = Table(sign_off_data, colWidths=[3.7*inch, 3.7*inch])
    t_sign.setStyle(TableStyle([
        ('BOX', (0,0), (-1,-1), 1, colors.black),
        ('INNERGRID', (0,0), (-1,-1), 0.5, colors.black),
        ('TOPPADDING', (0,0), (-1,-1), 2.5),
        ('BOTTOMPADDING', (0,0), (-1,-1), 2.5),
        ('LEFTPADDING', (0,0), (-1,-1), 4),
        ('RIGHTPADDING', (0,0), (-1,-1), 4),
        ('VALIGN', (0,0), (-1,-1), 'TOP'),
    ]))
    story.append(t_sign)
    story[sign_off_start:] = [KeepTogether(story[sign_off_start:])]

    # ── 8. SUPERVISORY OVERRIDE & STATUTORY JUSTIFICATION TRAIL (Seamless Flow) ──
    # Placed directly following the sign-off block without artificial page breaks!
    if officer_overrides and len(officer_overrides) > 0:
        override_intro_start = len(story)
        story.append(Spacer(1, 4))
        story.append(Paragraph("RECORDED OFFICER DECISIONS & JUSTIFICATIONS", title_style))
        story.append(Paragraph(f"Vendor: {vendor_name} | Evaluating Officer: {eval_officer} ({eval_designation}) | Local Decision Record", subtitle_style))
        story.append(HRFlowable(width="100%", thickness=1, color=colors.black, spaceBefore=1, spaceAfter=4))

        story.append(Paragraph(
            "<b>Prototype Decision Record:</b> "
            "This application requires a written justification for a changed check. Officer names are supplied display details; the record is not authenticated or cryptographically tamper-evident.",
            callout_style
        ))
        story.append(Spacer(1, 3))
        story[override_intro_start:] = [KeepTogether(story[override_intro_start:])]

        override_table_data = [
            [
                Paragraph("<b>Clause / Requirement</b>", body_bold),
                Paragraph("<b>Original</b>", body_bold),
                Paragraph("<b>Override Verdict</b>", body_bold),
                Paragraph("<b>Recorded Written Justification</b>", body_bold),
                Paragraph("<b>Timestamp</b>", body_bold)
            ]
        ]

        for cid, odata in officer_overrides.items():
            timestamp = odata.get("timestamp", "Not recorded")
            try:
                stamp = datetime.datetime.fromisoformat(timestamp)
                if stamp.tzinfo is not None:
                    stamp = stamp.astimezone(datetime.timezone.utc)
                    timestamp = stamp.strftime("%d-%b-%Y<br/>%H:%M:%S UTC")
            except (TypeError, ValueError):
                pass
            override_table_data.append([
                Paragraph(f"<b>{odata.get('clause_name', cid)}</b><br/>({cid})", body_style),
                Paragraph(f"{odata.get('original_status', 'N/A')}", body_style),
                Paragraph(f"<b>{odata.get('status', 'OVERRIDDEN')}</b>", body_style),
                Paragraph(f"{odata.get('justification', 'No justification provided.')}", body_style),
                Paragraph(timestamp, body_style)
            ])

        t_over = Table(override_table_data, colWidths=[1.5*inch, 0.8*inch, 1.0*inch, 2.9*inch, 1.2*inch])
        t_over.setStyle(TableStyle([
            ('BOX', (0,0), (-1,-1), 1, colors.black),
            ('INNERGRID', (0,0), (-1,-1), 0.5, colors.black),
            ('LINEBELOW', (0,0), (-1,0), 1.2, colors.black),
            ('TOPPADDING', (0,0), (-1,-1), 2.5),
            ('BOTTOMPADDING', (0,0), (-1,-1), 2.5),
            ('LEFTPADDING', (0,0), (-1,-1), 3.5),
            ('RIGHTPADDING', (0,0), (-1,-1), 3.5),
            ('VALIGN', (0,0), (-1,-1), 'TOP'),
        ]))
        story.append(t_over)
        story.append(Spacer(1, 4))

        # Officer Confirmation Box for Overrides with Manual Physical Sign-Off
        p2_sign_data = [
            [
                Paragraph(
                    f"<b>Optional Officer Acknowledgement:</b><br/>"
                    f"I, <b>{eval_officer}</b> ({eval_designation}), acknowledge that the justifications "
                    f"and decisions above reflect the recorded review. This prototype does not certify legal compliance or delegated authority.<br/><br/>"
                    f"_____________________________________________&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Date: ____________________<br/>"
                    f"<i>Manual officer signature (not digitally authenticated)</i>",
                    body_style
                )
            ]
        ]
        t_p2_sign = Table(p2_sign_data, colWidths=[7.4*inch])
        t_p2_sign.setStyle(TableStyle([
            ('BOX', (0,0), (-1,-1), 1, colors.black),
            ('TOPPADDING', (0,0), (-1,-1), 3),
            ('BOTTOMPADDING', (0,0), (-1,-1), 3),
            ('LEFTPADDING', (0,0), (-1,-1), 4),
            ('RIGHTPADDING', (0,0), (-1,-1), 4),
            ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
        ]))
        story.append(t_p2_sign)

    doc.build(story, canvasmaker=OfficialReportCanvas)
    return output_filepath
